version: "3.8"
services:
  flutter_web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    volumes:
      - .:/app
    environment:
      - PUB_HOSTED_URL=https://pub.flutter-io.cn
      - FLUTTER_STORAGE_BASE_URL=https://storage.flutter-io.cn
    restart: unless-stopped